import { useEffect, useState } from "react";
import { ImagePlus, Trash2, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { categories, finalPrice, money, stockStatus, type Order, type OrderStatus, type Product } from "@/lib/marketplace";
import { ProductImage, OrderStatusBadge } from "./Common";

export function ConfirmDialog({ trigger, title, description, onConfirm }: { trigger: React.ReactNode; title: string; description: string; onConfirm: () => void }) { const [open, setOpen] = useState(false); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild>{trigger}</DialogTrigger><DialogContent><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{description}</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button variant="destructive" onClick={() => { onConfirm(); setOpen(false); }}>Delete</Button></DialogFooter></DialogContent></Dialog>; }

export function ProductDialog({ product, onSave, trigger }: { product?: Product; onSave: (product: Product) => void; trigger: React.ReactNode }) {
  const empty: Product = { id: `p-${Date.now()}`, name: "", seller: "North & Pine", category: categories[0] ?? "Electronics", description: "", price: 0, discount: 0, stock: 0, imagePosition: "0% 0%" }; const [open, setOpen] = useState(false); const [draft, setDraft] = useState(product ?? empty); const [preview, setPreview] = useState<string | null>(null);
  useEffect(() => { if (open) { setDraft(product ?? { ...empty, id: `p-${Date.now()}` }); setPreview(null); } }, [open]);
  const field = (key: keyof Product, value: string | number) => setDraft((current) => ({ ...current, [key]: value }));
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild>{trigger}</DialogTrigger><DialogContent className="max-h-[92vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{product ? "Edit product" : "Add product"}</DialogTitle><DialogDescription>Product media and values remain local until your API is connected.</DialogDescription></DialogHeader><div className="grid gap-5 py-2 md:grid-cols-[180px_1fr]"><div><Label>Product image</Label><div className="mt-2 aspect-square overflow-hidden rounded-md border bg-muted">{preview ? <img src={preview} alt="Selected product preview" className="h-full w-full object-cover" /> : product ? <ProductImage product={product} className="h-full" /> : <div className="grid h-full place-items-center text-muted-foreground"><ImagePlus /></div>}</div><Input type="file" accept="image/*" className="mt-2" onChange={(event) => { const file = event.target.files?.[0]; if (file) setPreview(URL.createObjectURL(file)); }} /><Button variant="ghost" size="sm" className="mt-1 w-full" onClick={() => setPreview(null)}><Trash2 /> Remove image</Button></div><div className="grid gap-4"><div><Label htmlFor="name">Product name</Label><Input id="name" value={draft.name} onChange={(event) => field("name", event.target.value)} /></div><div><Label htmlFor="description">Description</Label><Textarea id="description" value={draft.description} onChange={(event) => field("description", event.target.value)} /></div><div><Label>Category</Label><Select value={draft.category} onValueChange={(value) => field("category", value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{categories.map((category) => <SelectItem value={category} key={category}>{category}</SelectItem>)}</SelectContent></Select></div><div className="grid grid-cols-3 gap-3"><div><Label>Price</Label><Input type="number" min="0" value={draft.price} onChange={(event) => field("price", Number(event.target.value))} /></div><div><Label>Discount %</Label><Input type="number" min="0" max="100" value={draft.discount} onChange={(event) => field("discount", Number(event.target.value))} /></div><div><Label>Stock</Label><Input type="number" min="0" value={draft.stock} onChange={(event) => field("stock", Number(event.target.value))} /></div></div><div className="rounded-md border bg-muted p-4"><div className="flex justify-between text-sm"><span className="text-muted-foreground">Final price</span><strong>{money(finalPrice(draft))}</strong></div><div className="mt-2 flex justify-between text-sm"><span className="text-muted-foreground">Stock status</span><strong>{stockStatus(draft.stock)}</strong></div></div></div></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button disabled={!draft.name || draft.price <= 0} onClick={() => { onSave(draft); setOpen(false); }}><Upload /> Save product</Button></DialogFooter></DialogContent></Dialog>;
}
export function CategoryDialog({ category, trigger, onSave }: { category?: string; trigger: React.ReactNode; onSave: (value: string) => void }) { const [value, setValue] = useState(category ?? ""); const [open, setOpen] = useState(false); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild>{trigger}</DialogTrigger><DialogContent><DialogHeader><DialogTitle>{category ? "Edit category" : "Add category"}</DialogTitle><DialogDescription>Categories organize products across the marketplace.</DialogDescription></DialogHeader><div><Label htmlFor="category">Category name</Label><Input id="category" value={value} onChange={(event) => setValue(event.target.value)} /></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={() => { onSave(value); setOpen(false); }}>Save category</Button></DialogFooter></DialogContent></Dialog>; }

export function OrderDetailsDialog({ order, trigger }: { order: Order; trigger: React.ReactNode }) { return <Dialog><DialogTrigger asChild>{trigger}</DialogTrigger><DialogContent><DialogHeader><DialogTitle>Order {order.id}</DialogTitle><DialogDescription>{order.date} · {order.customer}</DialogDescription></DialogHeader><div className="grid gap-3 rounded-md border p-4 text-sm"><Row label="Product" value={order.product} /><Row label="Seller" value={order.seller} /><Row label="Quantity" value={String(order.quantity)} /><Row label="Amount" value={money(order.amount)} /><div className="flex items-center justify-between"><span className="text-muted-foreground">Payment</span><span>{order.payment}</span></div><div className="flex items-center justify-between"><span className="text-muted-foreground">Order status</span><OrderStatusBadge status={order.status} /></div></div><div className="rounded-md bg-muted p-4"><p className="text-xs font-bold uppercase text-muted-foreground">Shipping information</p><p className="mt-2 text-sm">{order.customer}<br />128 Market Street<br />San Francisco, CA 94105</p></div></DialogContent></Dialog>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between gap-4"><span className="text-muted-foreground">{label}</span><span className="text-right font-medium">{value}</span></div>; }
export function OrderStatusDialog({ order, trigger, onSave }: { order: Order; trigger: React.ReactNode; onSave: (status: OrderStatus) => void }) { const [status, setStatus] = useState<OrderStatus>(order.status); return <Dialog><DialogTrigger asChild>{trigger}</DialogTrigger><DialogContent><DialogHeader><DialogTitle>Update order status</DialogTitle><DialogDescription>Changes will sync in real time after your Socket.IO backend is connected.</DialogDescription></DialogHeader><Select value={status} onValueChange={(value) => setStatus(value as OrderStatus)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["Pending", "Confirmed", "Processing", "Shipped", "Delivered"].map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select><DialogFooter><Button onClick={() => onSave(status)}>Update status</Button></DialogFooter></DialogContent></Dialog>; }